CREATE TABLE IF NOT EXISTS business (
		id INT AUTO_INCREMENT PRIMARY KEY,
		notificador VARCHAR(255) NOT NULL,
		folio VARCHAR(255) NOT NULL,
		contrato VARCHAR(20) NOT NULL,
		giro VARCHAR(255) NOT NULL,
		nombre VARCHAR(255) NOT NULL,
		direccion VARCHAR(255) NOT NULL,
		colonia VARCHAR(255) NOT NULL,
		fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		id_zona INT NOT NULL,
		estatus VARCHAR(255) NOT NULL,
		obs VARCHAR(255) NOT NULL
);
