CREATE TABLE IF NOT EXISTS notifiers (
		id INT AUTO_INCREMENT PRIMARY KEY,
		userid INT NOT NULL,
		name VARCHAR(255) NOT NULL,
		username VARCHAR(255) NOT NULL,
		password VARCHAR(500) NOT NULL,
		zone VARCHAR(50) NOT NULL,
		role VARCHAR(255) NOT NULL
);
